grails-app/controllers/com/luckydog/api/DealController.groovy
package com.luckydog.api

class DealController {

    def index() { }
	
	def show()
	{
		render (view:"/detail")
	}
}

grails-app/views/templates/flatize/_cart.gsp
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							
							<i class="fa fa-shopping-cart"></i> <span class="shopping-bag">9</span></a>
							<div class="dropdown-menu">
								<h3>Recently added item(s)</h3>
								<ul class="list-unstyled list-thumbs-pro">
									<li class="product">
										<div class="product-thumb-info">
											<a href="#" class="product-remove"><i class="fa fa-trash-o"></i></a>
											<div class="product-thumb-info-image">
												<a href="shop-product-detail1.html"><img alt="" width="60" src="<g:createLinkTo dir="/"  />images/flatize/content/products/product-1.jpg"></a>
											</div>
											
											<div class="product-thumb-info-content">
												<h4><a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />">Denim shirt</a></h4>
												<span class="item-cat"><small><a href="#">Jackets</a></small></span>
												<span class="price">29.99 USD</span>
											</div>
										</div>
									</li>
									<li class="product">
										<div class="product-thumb-info">
											<a href="#" class="product-remove"><i class="fa fa-trash-o"></i></a>
											<div class="product-thumb-info-image">
												<a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />"><img alt="" width="60" src="<g:createLinkTo dir="/"  />images/flatize/content/products/product-2.jpg"></a>
											</div>
											
											<div class="product-thumb-info-content">
												<h4><a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />">Poplin shirt with fine pleated bands</a></h4>
												<span class="item-cat"><small><a href="#">Jackets</a></small></span>
												<span class="price">29.99 USD</span>
											</div>
										</div>
									</li>
									<li class="product">
										<div class="product-thumb-info">
											<a href="#" class="product-remove"><i class="fa fa-trash-o"></i></a>
											<div class="product-thumb-info-image">
												<a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />"><img alt="" width="60" src="<g:createLinkTo dir="/"  />images/flatize/content/products/product-3.jpg"></a>
											</div>
											
											<div class="product-thumb-info-content">
												<h4><a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />">Contrasting shirt</a></h4>
												<span class="item-cat"><small><a href="#">Jackets</a></small></span>
												<span class="price">29.99 USD</span>
											</div>
										</div>
									</li>
								</ul>
								<ul class="list-inline cart-subtotals text-right">
									<li class="cart-subtotal"><strong>Subtotal</strong></li>
									<li class="price"><span class="amount"><strong>$431</strong></span></li>
								</ul>
								<div class="cart-buttons text-right">
									<button class="btn btn-white">View Cart</button>
									<button class="btn btn-primary">Checkout</button>
								</div>
							</div>

grails-app/views/templates/flatize/_footer.gsp
<footer class="footer">
			<div class="container">
				<div class="upper-foot">
					<div class="row">
						<div class="col-xs-6 col-sm-3">
							<h2>Contact detail</h2>
							<address>
								<i class="fa fa-map-marker"></i>1 Point Park Crescent<br>
								Docklands, Melbourne Australia<br>
								<i class="fa fa-phone"></i> Phone. 1300 HAGGELL<br>
								<i class="fa fa-fax"></i> Fax. (800) 456-7890<br>
								<i class="fa fa-envelope"></i> E-mail. <a href="mailto:#">haggell@alphasigma.com.au</a>
							</address>
						</div>
						<div class="col-xs-6 col-sm-3">
							<h2>Useful links</h2>
							<ul class="list-unstyled">
								<li><a href="#">Track Orders</a></li>
								<li><a href="#">FAQs</a></li>
								<li><a href="#">Services</a></li>
								<li><a href="#">Free Credit Report</a></li>
								<li><a href="#">Terms and Conditions</a></li>
								<li><a href="#">Privacy Policy</a></li>
								<li><a href="#">Community Guidelines</a></li>
							</ul>
						</div>
						<div class="col-xs-6 col-sm-3">
							<h2>Tags</h2>
							<ul class="list-inline tagclouds">
								<li><a href="#">Image</a></li>
								<li><a href="#">Features</a></li>
								<li><a href="#">Gallery</a></li>
								<li><a href="#">Post Formats</a></li>
								<li><a href="#">Typography</a></li>
								<li><a href="#">WooCommerce</a></li>
								<li><a href="#">Shortcodes</a></li>
								<li><a href="#">Best Sellers</a></li>
								<li><a href="#">Slideshow</a></li>
							</ul>
						</div>
						<div class="col-xs-6 col-sm-3">
							<h2>Don’t miss out</h2>
							<p>Subscribe for the best deals!</p>
							<form class="form-inline form-newsletter" role="form">
								<div class="form-group">
									<label class="sr-only" for="exampleInputEmail2">Email address</label>
									<input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter your email here">
								</div>
								<button type="submit" class="btn"><i class="fa fa-caret-right"></i></button>
							</form>
						</div>
					</div>
				</div>
				<div class="below-foot">
					<div class="row">
						<div class="col-xs-6 copyrights">
							<p>Copyright © 2014 Haggell . Designed by <a href="http://www.alphasigma.com.au/">AlphaSigma</a><br>
							All rights reserved.</p>
						</div>
						<div class="col-xs-6 text-right">
							<ul class="list-inline social-list">
								<li><a data-toggle="tooltip" data-placement="top" title="Facebook" href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a data-toggle="tooltip" data-placement="top" title="Twitter" href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a data-toggle="tooltip" data-placement="top" title="Google+" href="#"><i class="fa fa-google-plus"></i></a></li>
								<li><a data-toggle="tooltip" data-placement="top" title="Pinterest" href="#"><i class="fa fa-pinterest"></i></a></li>
								<li><a data-toggle="tooltip" data-placement="top" title="RSS" href="#"><i class="fa fa-rss"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</footer>

grails-app/views/templates/flatize/_login.gsp
<div class="login-wrapper">
	
	<ul role="tablist" class="nav nav-tabs pro-tabs">
		<li class="active"><a data-toggle="tab" role="tab" href="#login">Login</a></li>
		<li><a data-toggle="tab" role="tab" href="#register">Register</a></li>

	</ul>
	<div class="tab-content">
		<div id="login" class="tab-pane active">
			<form id="form-login" role="form">
					<div class="form-group">
					<label for="inputusername">Username</label> <input type="text"
						class="form-control input-lg" id="inputusername"
						placeholder="Username">
				</div>
				<div class="form-group">
					<label for="inputpassword">Password</label> <input type="password"
						class="form-control input-lg" id="inputpassword"
						placeholder="Password">
				</div>
				<ul class="list-inline">
					<li><button type="submit" class="btn btn-white">Log in</button></li>
					<li><a href="#">Request new password</a></li>
				</ul>
				
			</form>

 <a class="btn btn-block btn-social btn-twitter">
    <i class="fa fa-twitter"></i> Sign in with Twitter
  </a>

 <a class="btn btn-block btn-social btn-facebook">
    <i class="fa fa-facebook"></i> Sign in with Facebook
  </a>
  
   <a class="btn btn-block btn-social btn-google-plus">
    <i class="fa fa-google-plus"></i> Sign in with Google
  </a>
  
		</div>
		<div id="register" class="tab-pane">
			
			<form id="form-register" role="form">
				<h4>Register</h4>
						<div class="form-group">
					<label for="inputname">Name</label> <input type="text"
						class="form-control input-lg" id="inputname"
						placeholder="Your Name">
				</div>
				
					<div class="form-group">
					<label for="inputusername">Email</label> <input type="text"
						class="form-control input-lg" id="inputusername"
						placeholder="Your email">
				</div>
				<div class="form-group">
					<label for="inputpassword">Password</label> <input type="password"
						class="form-control input-lg" id="inputpassword"
						placeholder="Password">
				</div>
				
				<button type="submit" class="btn btn-white">Register</button>
			</form>
		</div>

	</div>


</div>

grails-app/views/templates/flatize/_nav.gsp
<nav class="navbar navbar-default navbar-main navbar-main-narrow" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
						<a class="logo" href="<g:createLinkTo dir="/"  />"><img src="<g:createLinkTo dir="/"  />images/newlogo.png" alt="Haggell"></a> </div>
					<ul class="nav nav-pills nav-top navbar-right navbar-act">
						<li class="login"><a href="javascript:void(0);"><i class="fa fa-user"></i></a></li>
						<li class="search"><a href="javascript:void(0);" data-toggle="modal" data-target=".bs-example-modal-lg"><i class="fa fa-search"></i></a></li>
						
						<li class="dropdown menu-shop">
						
					<g:render template="/templates/flatize/cart" />
							
							
						</li>
						
					</ul>
					<div class="navbar-collapse collapse width">
						<ul class="nav navbar-nav nav-white">
							<li class="dropdown active"> <a href="<g:createLinkTo dir="/"  />" >Home</a>
							</li>
							
							<li class="dropdown megamenu"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Shop</a>
								<div class="dropdown-menu">
									<div class="mega-menu-content">
										<div class="row">
											<div class="col-md-4 hidden-sm hidden-xs menu-column">
												<h3>Trends</h3>
												<ul class="list-unstyled sub-menu list-thumbs-pro">
													<li class="product">
														<div class="product-thumb-info">
															<div class="product-thumb-info-image">
																<a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />"><img alt="" width="60" src="<g:createLinkTo dir="/"  />images/flatize/content/products/product-1.jpg"></a>
															</div>
															
															<div class="product-thumb-info-content">
																<h4><a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />">Denim shirt</a></h4>
																<span class="item-cat"><small><a href="#">Jackets</a></small></span>
																<span class="price">29.99 USD</span>
															</div>
														</div>
													</li>
													<li class="product">
														<div class="product-thumb-info">
															<div class="product-thumb-info-image">
																<a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />"><img alt="" width="60" src="<g:createLinkTo dir="/"  />images/flatize/content/products/product-2.jpg"></a>
															</div>
															
															<div class="product-thumb-info-content">
																<h4><a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />">Poplin shirt with fine pleated bands</a></h4>
																<span class="item-cat"><small><a href="#">Jackets</a></small></span>
																<span class="price">29.99 USD</span>
															</div>
														</div>
													</li>
													<li class="product">
														<div class="product-thumb-info">
															<div class="product-thumb-info-image">
																<a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />"><img alt="" width="60" src="<g:createLinkTo dir="/"  />images/flatize/content/products/product-3.jpg"></a>
															</div>
															
															<div class="product-thumb-info-content">
																<h4><a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />">Contrasting shirt</a></h4>
																<span class="item-cat"><small><a href="#">Jackets</a></small></span>
																<span class="price">29.99 USD</span>
															</div>
														</div>
													</li>
												</ul>
											</div>
											<div class="col-md-2 menu-column">
												<h3>Man</h3>
												<ul class="list-unstyled sub-menu">
													<li><a href="#">Jackets</a></li>
													<li><a href="#">Blazers</a></li>
													<li><a href="#">Suits</a></li>
													<li><a href="#">Trousers</a></li>
													<li><a href="#">Jeans</a></li>
													<li><a href="#">Shirts</a></li>
													<li><a href="#">Sweatshirts &amp; Hoodies</a></li>
													<li><a href="#">Swimwear</a></li>
													<li><a href="#">Accessories</a></li>
												</ul>
											</div>
											
											<div class="col-md-2 menu-column">
												<h3>Woman</h3>
												<ul class="list-unstyled sub-menu">
													<li><a href="#">Coats</a></li>
													<li><a href="#">Outerwear</a></li>
													<li><a href="#">Dresses</a></li>
													<li><a href="#">Tops</a></li>
													<li><a href="#">Trousers</a></li>
													<li><a href="#">Shirts</a></li>
													<li><a href="#">Jeans</a></li>
													<li><a href="#">T-shirts</a></li>
													<li><a href="#">Shoes</a></li>
													<li><a href="#">Handbags</a></li>
													<li><a href="#">Stock clearance</a></li>
												</ul>
											</div>
											<div class="col-md-4 hidden-sm hidden-xs menu-column">
												<h3>Explore new collection</h3>
												<ul class="list-unstyled sub-menu list-md-pro">
													<li class="product">
														<div class="product-thumb-info">
															<div class="product-thumb-info-image">
																<a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />"><img class="img-responsive" width="330" alt="" src="<g:createLinkTo dir="/"  />images/flatize/content/products/ad-1.png"></a>
															</div>
															
															<div class="product-thumb-info-content">
																<h4><a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />">Men’s Fashion and Style</a></h4>
																<p>Whatever you’re looking for, be it the latest fashion trends, cool outfit ideas or new ways to wear your favourite pieces, we’ve got all the style inspiration you need.</p>
															</div>
														</div>
													</li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</li>
							
									<!-- 	
							
							<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages</a>
								<ul class="dropdown-menu">
									<li class="dropdown-submenu">
										<a href="#">Shop</a>
										<ul class="dropdown-menu">
											<li><a href="shop-full-width.html">Shop - Full Width</a></li>
											<li><a href="shop-sidebar.html">Shop - Sidebar</a></li>
											<li><a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />">Shop - Product Detail 1</a></li>
											<li><a href="<g:createLink controller="deal" action="show" params="[adid:'1']" />">Shop - Product Detail 2</a></li>
											<li><a href="shop-cart-full.html">Shop - Cart Full</a></li>
											<li><a href="shop-cart-sidebar.html">Shop - Cart Sidebar</a></li>
											<li><a href="shop-checkout.html">Shop - Checkout</a></li>
										</ul>
									</li>
									<li><a href="index-white.html">Mega Menu White</a></li>
									<li><a href="page-404.html">404 Error Page</a></li>									
								</ul>
							</li>
							
							
							
				
							<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog</a>
								<ul class="dropdown-menu">
									<li><a href="blog-sidebar.html">Blog Sidebar</a></li>
									<li><a href="blog-mini-sidebar.html">Blog Mini Sidebar</a></li>
									<li><a href="blog-masonry.html">Blog Masonry</a></li>
									<li><a href="blog-single.html">Blog Single</a></li>
								</ul>
							</li> -->
							
							<li><a href="<g:createLinkTo dir="/"  />shopper/profile">My Profile</a></li>
							<li><a href="<g:createLinkTo dir="/"  />contactus" >Contact</a>
								
							</li>
							
						</ul>
					</div><!--/.nav-collapse --> 
				</div><!--/.container-fluid --> 
			</nav>
		
		

grails-app/views/templates/flatize/_search.gsp
		<!-- Begin Search -->
	<div class="modal fade bs-example-modal-lg search-wrapper" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<p class="clearfix"><button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button></p>
				<form class="form-inline form-search" role="form">
					<div class="form-group">
						<label class="sr-only" for="textsearch">Enter text search</label>
						<input type="text" class="form-control input-lg" id="textsearch" placeholder="Enter text search">
					</div>
					<button type="submit" class="btn btn-white">Search</button>
				</form>
			</div>
		</div>
	</div>
	<!-- End Search -->

grails-app/views/templates/flatize/_styleswitch.gsp
	<!-- Begin Style Switcher -->
	<div id="style-switcher">
		<div id="toggle_button"> <a href="#"><i class="fa fa-pencil"></i></a> </div>
		<div id="style-switcher-menu">
			<h4 class="text-center">Style Switcher</h4>
			<div class="segment">
				<ul class="theme cookie_layout_style level-0" id="bd_value">
					<li> <a style="background: #3598db" title="colors/blue/style" href="#"></a> </li>
					<li> <a style="background: #c2a772" title="colors/brown/style" href="#"></a> </li>
					<li> <a style="background: #36c877" title="colors/green/style" href="#"></a> </li>
					<li> <a style="background: #e99b1f" title="colors/orange/style" href="#"></a> </li>
					<li> <a style="background: #f64243" title="colors/red/style" href="#"></a> </li>
					<li> <a style="background: #a57bcd" title="colors/violet/style" href="#"></a> </li>
					<li> <a style="background: #e9bf1d" title="colors/yellow/style" href="#"></a> </li>
				</ul>
			</div>
			<div class="segment">
				<div id="reset"> <a href="#" class="btn btn-sm reset">Reset</a> </div>
			</div>
		</div>
	
	<!-- Begin Style Switcher -->
	
	</div>

grails-app/views/templates/flatize/_top.gsp
		<div id="top">
				<div class="container">
					<p class="pull-left text-note" style="text:white">	
			
			<!--  Change the foreground to white -->
				<ul class="nav navbar-nav nav-white">
					<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Select City</a>
								<ul class="dropdown-menu">
									<li class="dropdown-submenu">
										<a href="#">Victoria</a>
										<ul class="dropdown-menu">
											<li><a href="#">Melbourne</a></li>
											<li><a href="#">Geelong</a></li>
											<li><a href="#">Ballarat</a></li>
											<li><a href="#">Mornington Peninsula</a></li>
										</ul>
									</li>
									
									<li class="dropdown-submenu">
										<a href="#">New South Wales</a>
										<ul class="dropdown-menu">
											<li><a href="#">Sydney</a></li>
											<li><a href="#">Aubury</a></li>
											<li><a href="#">Wagga Wagga</a></li>
											<li><a href="#">Brooklyn</a></li>
										</ul>
									</li>
									
										<li class="dropdown-submenu">
										<a href="#">Queensland</a>
										<ul class="dropdown-menu">
											<li><a href="#">Cairns</a></li>
											<li><a href="#">Airlie Beach</a></li>
											<li><a href="#">Byron Bay</a></li>
											<li><a href="#">Sunshine Coast</a></li>
										</ul>
									</li>
									
																	
								</ul>
							</li>
							</ul>
							
							</p>
					<ul class="nav nav-pills nav-top navbar-right">
						<li class="dropdown langs">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="<g:createLinkTo dir="/"  />images/flatize/flags/en.gif" alt="English"> <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="#"><img src="<g:createLinkTo dir="/"  />images/flatize/flags/ar.gif" alt="AR"></a></li>
								<li><a href="#"><img src="<g:createLinkTo dir="/"  />images/flatize/flags/ca.gif" alt="CA"></a></li>
								<li><a href="#"><img src="<g:createLinkTo dir="/"  />images/flatize/flags/de.gif" alt="DE"></a></li>
								<li><a href="#"><img src="<g:createLinkTo dir="/"  />images/flatize/flags/es.gif" alt="ES"></a></li>
								<li><a href="#"><img src="<g:createLinkTo dir="/"  />images/flatize/flags/et.gif" alt="ET"></a></li>
								<li><a href="#"><img src="<g:createLinkTo dir="/"  />images/flatize/flags/fa.gif" alt="FA"></a></li>
								<li><a href="#"><img src="<g:createLinkTo dir="/"  />images/flatize/flags/fr.gif" alt="FR"></a></li>
								<li><a href="#"><img src="<g:createLinkTo dir="/"  />images/flatize/flags/ja.gif" alt="JA"></a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>